In [95]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [96]:
df=pd.read_csv("../../data/raw/v2/sofascore_top5_2324season.csv")

In [97]:
df.shape

(2777, 117)

In [98]:
per90_cols = [
    # Finishing
    "goals",
    "expectedGoals",
    "totalShots",
    "shotsOnTarget",
    "shotsOffTarget",
    "shotsFromInsideTheBox",
    "shotsFromOutsideTheBox",
    "hitWoodwork",
    "leftFootGoals",
    "rightFootGoals",
    "headedGoals",
    "goalsFromInsideTheBox",
    "goalsFromOutsideTheBox",
    "freeKickGoal",
    "penaltiesTaken",
    "penaltyGoals",
    "bigChancesMissed",

    # Creativity
    "assists",
    "expectedAssists",
    "goalsAssistsSum",
    "totalPasses",
    "accuratePasses",
    "inaccuratePasses",
    "totalOppositionHalfPasses",
    "accurateOppositionHalfPasses",
    "totalOwnHalfPasses",
    "accurateOwnHalfPasses",
    "accurateFinalThirdPasses",
    "keyPasses",
    "totalAttemptAssist",
    "passToAssist",
    "bigChancesCreated",
    "totalLongBalls",
    "accurateLongBalls",
    "totalChippedPasses",
    "accurateChippedPasses",
    "totalCross",
    "accurateCrosses",

    # Possession
    "touches",
    "possessionLost",
    "dispossessed",
    "totalContest",
    "successfulDribbles",
    "offsides",
    "wasFouled",
    "fouls",

    # Defensive
    "tackles",
    "tacklesWon",
    "interceptions",
    "ballRecovery",
    "possessionWonAttThird",
    "clearances",
    "outfielderBlocks",
    "blockedShots",
    "dribbledPast",
    "errorLeadToShot",
    "errorLeadToGoal",

    # Duels
    "totalDuelsWon",
    "duelLost",
    "groundDuelsWon",
    "aerialDuelsWon",
    "aerialLost",

    # Discipline
    "yellowCards",
    "yellowRedCards",
    "directRedCards",
    "ownGoals"
]

In [99]:
rate_cols = [
    "goalConversionPercentage",
    "scoringFrequency",

    "accuratePassesPercentage",
    "accurateLongBallsPercentage",
    "successfulDribblesPercentage",

    "tacklesWonPercentage",

    "totalDuelsWonPercentage",
    "groundDuelsWonPercentage",
    "aerialDuelsWonPercentage",

    "penaltyConversion",

    "rating",
    "totalRating",
    "countRating"
]

In [100]:
df["rating"].head()

0    8.00
1    7.40
2    7.36
3    7.21
4    7.21
Name: rating, dtype: float64

In [101]:
print(df.columns.tolist())

['accurateChippedPasses', 'accurateCrosses', 'accurateCrossesPercentage', 'accurateFinalThirdPasses', 'accurateLongBalls', 'accurateLongBallsPercentage', 'accurateOppositionHalfPasses', 'accurateOwnHalfPasses', 'accuratePasses', 'accuratePassesPercentage', 'aerialDuelsWon', 'aerialDuelsWonPercentage', 'aerialLost', 'appearances', 'assists', 'attemptPenaltyMiss', 'attemptPenaltyPost', 'attemptPenaltyTarget', 'ballRecovery', 'bigChancesCreated', 'bigChancesMissed', 'blockedShots', 'cleanSheet', 'clearances', 'countRating', 'crossesNotClaimed', 'directRedCards', 'dispossessed', 'dribbledPast', 'duelLost', 'errorLeadToGoal', 'errorLeadToShot', 'expectedAssists', 'expectedGoals', 'fouls', 'freeKickGoal', 'goalConversionPercentage', 'goalKicks', 'goals', 'goalsAssistsSum', 'goalsConceded', 'goalsConcededInsideTheBox', 'goalsConcededOutsideTheBox', 'goalsFromInsideTheBox', 'goalsFromOutsideTheBox', 'goalsPrevented', 'groundDuelsWon', 'groundDuelsWonPercentage', 'headedGoals', 'highClaims', 'hitWoodwork', 'inaccuratePasses', 'interceptions', 'keyPasses', 'leftFootGoals', 'matchesStarted', 'minutesPlayed', 'offsides', 'outfielderBlocks', 'ownGoals', 'passToAssist', 'penaltiesTaken', 'penaltyConceded', 'penaltyConversion', 'penaltyFaced', 'penaltyGoals', 'penaltySave', 'penaltyWon', 'possessionLost', 'possessionWonAttThird', 'punches', 'rating', 'redCards', 'rightFootGoals', 'runsOut', 'savedShotsFromInsideTheBox', 'savedShotsFromOutsideTheBox', 'saves', 'savesCaught', 'savesParried', 'scoringFrequency', 'setPieceConversion', 'shotFromSetPiece', 'shotsFromInsideTheBox', 'shotsFromOutsideTheBox', 'shotsOffTarget', 'shotsOnTarget', 'successfulDribbles', 'successfulDribblesPercentage', 'successfulRunsOut', 'tackles', 'tacklesWon', 'tacklesWonPercentage', 'totalAttemptAssist', 'totalChippedPasses', 'totalContest', 'totalCross', 'totalDuelsWon', 'totalDuelsWonPercentage', 'totalLongBalls', 'totalOppositionHalfPasses', 'totalOwnHalfPasses', 'totalPasses', 'totalRating', 'totalShots', 'totwAppearances', 'touches', 'wasFouled', 'yellowCards', 'yellowRedCards', 'player', 'team', 'player id', 'team id', 'league', 'season', 'position']

In [102]:
for col in per90_cols:
    df[f"{col}_per90"] = np.where(
        df["minutesPlayed"] > 0,
        (df[col] / df["minutesPlayed"]) * 90,
        np.nan
    )

C:\Users\vibha\AppData\Local\Temp\ipykernel_17272\1234406280.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"{col}_per90"] = np.where(

In [103]:
df.shape

(2777, 183)

In [104]:
df.shape
df.isna().sum().sort_values(ascending=False).head(20)

goalsPrevented                  2577
outfielderBlocks_per90          2207
outfielderBlocks                2207
expectedGoals                    220
expectedGoals_per90              220
expectedAssists_per90             21
expectedAssists                   21
goalKicks                         19
ballRecovery                      19
ballRecovery_per90                19
accuratePassesPercentage           0
accurateOppositionHalfPasses       0
accurateOwnHalfPasses              0
appearances                        0
aerialDuelsWon                     0
assists                            0
attemptPenaltyMiss                 0
attemptPenaltyPost                 0
accuratePasses                     0
aerialDuelsWonPercentage           0
dtype: int64

In [105]:
df[df["expectedGoals"].isna()][
    ["player", "team", "league", "season", "position"]
].head(20)

,player,team,league,season,position
0,Arijanet Murić,Burnley,England Premier League,23/24,Goalkeepers
5,Martin Dúbravka,Newcastle United,England Premier League,23/24,Goalkeepers
6,Mark Travers,Bournemouth,England Premier League,23/24,Goalkeepers
16,Łukasz Fabiański,West Ham United,England Premier League,23/24,Goalkeepers
18,James Shea,Luton Town,England Premier League,23/24,Goalkeepers
24,Caoimhin Kelleher,Liverpool FC,England Premier League,23/24,Goalkeepers
25,Stefan Ortega,Manchester City,England Premier League,23/24,Goalkeepers
26,Đorđe Petrović,Chelsea,England Premier League,23/24,Goalkeepers
29,Dean Henderson,Crystal Palace,England Premier League,23/24,Goalkeepers
31,Ivo Grbić,Sheffield United,England Premier League,23/24,Goalkeepers
33,Odysseas Vlachodimos,Nottingham Forest,England Premier League,23/24,Goalkeepers
34,Matz Sels,Nottingham Forest,England Premier League,23/24,Goalkeepers
36,Daniel Bentley,Wolverhampton,England Premier League,23/24,Goalkeepers
37,Loris Karius,Newcastle United,England Premier League,23/24,Goalkeepers
38,Remi Matthews,Crystal Palace,England Premier League,23/24,Goalkeepers
39,Ionuț Radu,Bournemouth,England Premier League,23/24,Goalkeepers
77,Josh Acheampong,Chelsea,England Premier League,23/24,Defenders
175,Séamus Coleman,Everton,England Premier League,23/24,Defenders
191,Santiago Bueno,Wolverhampton,England Premier League,23/24,Defenders
193,Owen Beck,Liverpool FC,England Premier League,23/24,Defenders

In [106]:
df[df["expectedGoals"].isna()]["position"].value_counts()

position
Goalkeepers    76
Midfielders    58
Defenders      52
Forwards       34
Name: count, dtype: int64

In [107]:
df[
    (df["position"] == "Forwards") &
    (df["expectedGoals"].isna())
][
    ["player", "team", "league", "season", "minutesPlayed", "goals"]
].sort_values(
    "minutesPlayed",
    ascending=False
).head(50)

,player,team,league,season,minutesPlayed,goals
1649,Jean-Mattéo Bahoya,Eintracht Frankfurt,Germany Bundesliga,23/24,175,0
2243,David Ankeye,Genoa,Italy Serie A,23/24,64,0
559,Dane Scarlett,Tottenham Hotspur,England Premier League,23/24,42,0
1107,Jastin García,Girona FC,Spain La Liga,23/24,31,0
554,Rodrigo Ribeiro,Nottingham Forest,England Premier League,23/24,28,0
553,Ethan Wheatley,Manchester United,England Premier League,23/24,28,0
1656,Julien Duranville,Borussia Dortmund,Germany Bundesliga,23/24,26,0
547,Jayden Danns,Liverpool FC,England Premier League,23/24,26,0
2771,Andrej Ilić,Lille,France Ligue 1,23/24,21,0
2220,Andres Șfaiț,Salernitana,Italy Serie A,23/24,21,0
552,Daniel Jebbison,Sheffield United,England Premier League,23/24,20,0
561,Mikey Moore,Tottenham Hotspur,England Premier League,23/24,20,0
2773,Mohamed Bechikh,RC Strasbourg,France Ligue 1,23/24,19,0
1094,Pablo Sáenz,Granada,Spain La Liga,23/24,18,0
565,Ryan One,Sheffield United,England Premier League,23/24,18,0
2765,Patrick Ouotro,RC Strasbourg,France Ligue 1,23/24,17,0
2237,Yayah Kallon,Hellas Verona,Italy Serie A,23/24,15,0
2238,Gerardo Fusco,Salernitana,Italy Serie A,23/24,14,0
1155,Salim El Jebari,Atlético Madrid,Spain La Liga,23/24,12,0
2236,Alphadjo Cissè,Hellas Verona,Italy Serie A,23/24,11,0
1651,Max Moerstedt,TSG Hoffenheim,Germany Bundesliga,23/24,11,0
1156,Jeremy Jorge,Getafe,Spain La Liga,23/24,10,0
1659,Bennit Bröger,VfL Wolfsburg,Germany Bundesliga,23/24,10,0
2766,Adel Mahamoud,Nantes,France Ligue 1,23/24,9,0
2764,Lucas Michal,AS Monaco,France Ligue 1,23/24,9,0
1164,Abde Raihani,Atlético Madrid,Spain La Liga,23/24,9,0
544,Enso González,Wolverhampton,England Premier League,23/24,8,0
1165,Yassin Tallal,Getafe,Spain La Liga,23/24,8,0
1166,Max Svensson,Osasuna,Spain La Liga,23/24,2,0
566,Kaide Gordon,Liverpool FC,England Premier League,23/24,1,0
568,Michael Ndiweni,Newcastle United,England Premier League,23/24,1,0
567,Amadou Diallo,Newcastle United,England Premier League,23/24,1,0
1660,Jonathan Asp Jensen,FC Bayern München,Germany Bundesliga,23/24,1,0
1661,Joel Imasuen,SV Werder Bremen,Germany Bundesliga,23/24,1,0