In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [6]:
df_26=pd.read_csv("../../data/raw/v2/sofascore_top5_2526season.csv")
df_25=pd.read_csv("../../data/raw/v2/sofascore_top5_2425season.csv")
df_24=pd.read_csv("../../data/raw/v2/sofascore_top5_2324season.csv")

## First Cleaning Players who moved Mid-Season ##

In [14]:
df=[df_26,df_25,df_24]

for d in df:
    total_rows = len(d)
    unique_ids = d['player'].nunique()
    duplicate_count = total_rows - unique_ids
    print(duplicate_count)

85
71
72

In [16]:
df_26.columns.tolist()

['accurateChippedPasses',
 'accurateCrosses',
 'accurateCrossesPercentage',
 'accurateFinalThirdPasses',
 'accurateLongBalls',
 'accurateLongBallsPercentage',
 'accurateOppositionHalfPasses',
 'accurateOwnHalfPasses',
 'accuratePasses',
 'accuratePassesPercentage',
 'aerialDuelsWon',
 'aerialDuelsWonPercentage',
 'aerialLost',
 'appearances',
 'assists',
 'attemptPenaltyMiss',
 'attemptPenaltyPost',
 'attemptPenaltyTarget',
 'ballRecovery',
 'bigChancesCreated',
 'bigChancesMissed',
 'blockedShots',
 'cleanSheet',
 'clearances',
 'countRating',
 'crossesNotClaimed',
 'directRedCards',
 'dispossessed',
 'dribbledPast',
 'duelLost',
 'errorLeadToGoal',
 'errorLeadToShot',
 'expectedAssists',
 'expectedGoals',
 'fouls',
 'freeKickGoal',
 'goalConversionPercentage',
 'goalKicks',
 'goals',
 'goalsAssistsSum',
 'goalsConceded',
 'goalsConcededInsideTheBox',
 'goalsConcededOutsideTheBox',
 'goalsFromInsideTheBox',
 'goalsFromOutsideTheBox',
 'goalsPrevented',
 'groundDuelsWon',
 'groundDuelsWonPercentage',
 'headedGoals',
 'highClaims',
 'hitWoodwork',
 'inaccuratePasses',
 'interceptions',
 'keyPasses',
 'leftFootGoals',
 'matchesStarted',
 'minutesPlayed',
 'offsides',
 'outfielderBlocks',
 'ownGoals',
 'passToAssist',
 'penaltiesTaken',
 'penaltyConceded',
 'penaltyConversion',
 'penaltyFaced',
 'penaltyGoals',
 'penaltySave',
 'penaltyWon',
 'possessionLost',
 'possessionWonAttThird',
 'punches',
 'rating',
 'redCards',
 'rightFootGoals',
 'runsOut',
 'savedShotsFromInsideTheBox',
 'savedShotsFromOutsideTheBox',
 'saves',
 'savesCaught',
 'savesParried',
 'scoringFrequency',
 'setPieceConversion',
 'shotFromSetPiece',
 'shotsFromInsideTheBox',
 'shotsFromOutsideTheBox',
 'shotsOffTarget',
 'shotsOnTarget',
 'successfulDribbles',
 'successfulDribblesPercentage',
 'successfulRunsOut',
 'tackles',
 'tacklesWon',
 'tacklesWonPercentage',
 'totalAttemptAssist',
 'totalChippedPasses',
 'totalContest',
 'totalCross',
 'totalDuelsWon',
 'totalDuelsWonPercentage',
 'totalLongBalls',
 'totalOppositionHalfPasses',
 'totalOwnHalfPasses',
 'totalPasses',
 'totalRating',
 'totalShots',
 'totwAppearances',
 'touches',
 'wasFouled',
 'yellowCards',
 'yellowRedCards',
 'player',
 'team',
 'player id',
 'team id',
 'league',
 'season',
 'position']

In [35]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(df_26[df_26.duplicated(subset=['player id'], keep=False)].drop_duplicates(subset=['player id'])[['player id', 'player']])

      player id                 player
68      1088897           Jenson Seelt
79      1002837         Piero Hincapié
107     1471671          Jaydee Canvot
110     1184308           Álex Jiménez
137      856250        Ladislav Krejčí
142     1050692          Diego Coppola
146      979144              Luca Netz
167      174975         Arthur Masuaku
213     1154657           Mamadou Sarr
215      877102           Nayef Aguerd
242       48480            Pascal Groß
274      997183            Xavi Simons
330     1401702          Ethan Nwaneri
338      891829           Matt O'Riley
340      867441            Angel Gomes
352      904970        Conor Gallagher
362      894733       Marshall Munetsi
367     1198075           Brajan Gruda
374      609752        Guido Rodríguez
391      808590            Leon Bailey
402      963298           Dilane Bakwa
403     1064082            Merlin Röhl
405     1526628              Fer López
409     1110842          Simon Adingra
410      892924    Hamed Junior Traorè
444      822470       Samuel Chukwueze
449      984624            Yéremy Pino
463      877013   Valentín Castellanos
474      980623         Nick Woltemade
477      962364          Lorenzo Lucca
478      803039          Donyell Malen
493      795228        Odsonne Édouard
502      829570          Jack Harrison
521     1503757       Jonah Kusi-Asare
522     1884145       Christantus Uche
529      954061      Arnaud Kalimuendo
535      132645        Niclas Füllkrug
688      892521             Unai Núñez
831      901325       Nicolás González
847     1170694          Ugo Raghouber
905     1482424      Claudio Echeverri
914      158615          Matías Vecino
962     1926085         Dro Fernández
995     1484974    Justin-Noel Kalumba
1006    1149152  Stanis Idumbo Muzambo
1028    1009372     Georges Mikautadze
1042    1084730         Bryan Zaragoza
1050     862223          Manor Solomon
1052     973536        Martín Satriano
1056     824200        Ademola Lookman
1065    1000150           Zito Luvumbo
1066    1174937                Endrick
1077     268903            Neal Maupay
1078     605374           Tete Morente
1085     877037           Cyril Ngonge
1094    1216282          Luca Koleosho
1101     891505      Goduine Koyalipou
1104     352544        Sheraldo Becker
1113     865651      Giacomo Raspadori
1176    1500263        Aarón Anselmino
1198     355486           Stefan Posch
1297    1155226           Saël Kumbedi
1355    1000263         Albert Grønbæk
1380     929620          Fabian Rieder
1487    1153265     Badredine Bouanani
1538    1394353     Eliesse Ben Seghir
1555     848458          Arnaud Nordin
1558     835480            Loïs Openda
1622     979315              Elye Wahi
1682     787505        Benjamin Pavard
1730     558320         Ulisses Garcia
1766    1002564           Mikayil Faye
1844     844480             Pol Lirola
1857     250737          Adrien Rabiot
1942    1823916          Darryl Bakola
1964    1048889             Andy Diouf
2005    1127590           Mohamed Kaba
2074     367056           Jérémie Boga
2105    1065261          Jonathan Rowe
2170    1514800            Robinio Vaz
2174    1536811          Idrissa Gueye
2218      45923          Ciro Immobile

In [31]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(df_26[['team', 'team id']].drop_duplicates().dropna())

                        team  team id
0                    Burnley        6
1            Manchester City       17
2             Crystal Palace        7
3          Nottingham Forest       14
4              Wolverhampton        3
5                  Brentford       50
6     Brighton & Hove Albion       30
7               Leeds United       34
9          Manchester United       35
10                   Everton       48
11                   Arsenal       42
12                Sunderland       41
15               Aston Villa       40
16              Liverpool FC       44
18                    Fulham       43
19                   Chelsea       38
21          Newcastle United       39
23               Bournemouth       60
24         Tottenham Hotspur       33
28           West Ham United       37
537               Real Betis     2816
538                 Espanyol     2814
539               Levante UD     2849
540           Rayo Vallecano     2818
541            Real Sociedad     2824
542                  Osasuna     2820
543                    Elche     2846
544             FC Barcelona     2817
546              Real Oviedo     2851
547                   Getafe     2859
550                Girona FC    24264
551          Atlético Madrid     2836
552              Real Madrid     2829
554                 Valencia     2828
555                 Mallorca     2826
558               Villarreal     2819
560               Celta Vigo     2821
563                  Sevilla     2833
566         Deportivo Alavés     2885
569            Athletic Club     2825
1137      1. FC Union Berlin     2547
1138            Hamburger SV     2676
1139        1. FC Heidenheim     5885
1140       FC Bayern München     2672
1141        SV Werder Bremen     2534
1142         1. FSV Mainz 05     2556
1143     Borussia M'gladbach     2527
1144     Bayer 04 Leverkusen     2681
1146           VfL Wolfsburg     2524
1147           VfB Stuttgart     2677
1150       Borussia Dortmund     2673
1151              1. FC Köln     2671
1153            FC St. Pauli     2526
1154             SC Freiburg     2538
1155              RB Leipzig    36360
1156             FC Augsburg     2600
1157     Eintracht Frankfurt     2674
1163          TSG Hoffenheim     2569
1636              Fiorentina     2693
1637                   Parma     2690
1638                Atalanta     2686
1639                AC Milan     2692
1640                    Como     2704
1641                   Lazio     2699
1642                 Bologna     2685
1643                Sassuolo     2793
1644                 AS Roma     2702
1645                  Torino     2696
1647                    Pisa     2737
1648               Cremonese     2761
1650                Cagliari     2719
1651                   Lecce     2689
1652                 Udinese     2695
1657                   Genoa     2713
1658                   Inter     2697
1660                Juventus     2687
1664              SSC Napoli     2714
1670           Hellas Verona     2701
2222                 RC Lens     1648
2223                Le Havre     1662
2224      Olympique Lyonnais     1649
2225                  Nantes     1647
2226                  Angers     1684
2227           RC Strasbourg     1659
2228                   Lille     1643
2229     Paris Saint-Germain     1644
2230          Stade Brestois     1715
2233  Olympique de Marseille     1641
2235                    Nice     1661
2236                 Auxerre     1646
2239                    Metz     1651
2240                 Lorient     1656
2243           Stade Rennais     1658
2244                Paris FC     6070
2246               AS Monaco     1653
2250                Toulouse     1681
2282           Saint-Étienne     1678
2603                Rodez AF     6925

In [36]:
player_team_ids = {
    1088897: 2524,
    1002837: 42,
    1471671: 7,
    1184308: 60,
    856250: 3,
    1050692: 6070,
    979144: 14,
    174975: 41,
    1154657: 38,
    877102: 1641,
    48480: 30,
    997183: 33,
    1401702: 1641,
    891829: 30,
    867441: 3,
    904970: 33,
    894733: 6070,
    1198075: 36360,
    609752: 2828,
    808590: 40,
    963298: 14,
    1064082: 48,
    1526628: 2821,
    1110842: 1653,
    892924: 1641,
    822470: 43,
    984624: 7,
    877013: 37,
    980623: 39,
    962364: 14,
    803039: 2702,
    795228: 1648,
    829570: 2693,
    1503757: 43,
    1884145: 7,
    954061: 2674,
    132645: 2692,
    892521: 2828,
    901325: 2836,
    1170694: 2849,
    1482424: 24264,
    158615: 2821,
    1926085: 1644,
    1484974: 2826,
    1149152: 1653,
    1009372: 2819,
    1084730: 2702,
    862223: 2693,
    973536: 2859,
    824200: 2836,
    1000150: 2826,
    1174937: 1649,
    268903: 2833,
    605374: 2846,
    877037: 2814,
    1216282: 6070,
    891505: 1684,
    352544: 2556,
    865651: 2686,
    1500263: 1659,
    355486: 2556,
    1155226: 2524,
    1000263: 2676,
    929620: 2600,
    1153265: 2677,
    1394353: 2681,
    848458: 1658,
    835480: 2687,
    979315: 1661,
    787505: 1641,
    558320: 2793,
    1002564: 2761,
    844480: 2701,
    250737: 2692,
    1823916: 2793,
    1048889: 2697,
    1127590: 1647,
    367056: 2687,
    1065261: 2685,
    1514800: 2702,
    1536811: 48,
    45923: 6070
}

In [49]:
team_id_to_name={}
for id in player_team_ids.values():
    team_id_to_name.setdefault(id,df_26[df_26['team id'] == id]['team'].unique())

In [51]:
team_id_to_name = df_26.groupby('team id')['team'].first().to_dict()

In [52]:
team_id_to_name

{3: 'Wolverhampton',
 6: 'Burnley',
 7: 'Crystal Palace',
 14: 'Nottingham Forest',
 17: 'Manchester City',
 30: 'Brighton & Hove Albion',
 33: 'Tottenham Hotspur',
 34: 'Leeds United',
 35: 'Manchester United',
 37: 'West Ham United',
 38: 'Chelsea',
 39: 'Newcastle United',
 40: 'Aston Villa',
 41: 'Sunderland',
 42: 'Arsenal',
 43: 'Fulham',
 44: 'Liverpool FC',
 48: 'Everton',
 50: 'Brentford',
 60: 'Bournemouth',
 1641: 'Olympique de Marseille',
 1643: 'Lille',
 1644: 'Paris Saint-Germain',
 1646: 'Auxerre',
 1647: 'Nantes',
 1648: 'RC Lens',
 1649: 'Olympique Lyonnais',
 1651: 'Metz',
 1653: 'AS Monaco',
 1656: 'Lorient',
 1658: 'Stade Rennais',
 1659: 'RC Strasbourg',
 1661: 'Nice',
 1662: 'Le Havre',
 1678: 'Saint-Étienne',
 1681: 'Toulouse',
 1684: 'Angers',
 1715: 'Stade Brestois',
 2524: 'VfL Wolfsburg',
 2526: 'FC St. Pauli',
 2527: "Borussia M'gladbach",
 2534: 'SV Werder Bremen',
 2538: 'SC Freiburg',
 2547: '1. FC Union Berlin',
 2556: '1. FSV Mainz 05',
 2569: 'TSG Hoffenheim',
 2600: 'FC Augsburg',
 2671: '1. FC Köln',
 2672: 'FC Bayern München',
 2673: 'Borussia Dortmund',
 2674: 'Eintracht Frankfurt',
 2676: 'Hamburger SV',
 2677: 'VfB Stuttgart',
 2681: 'Bayer 04 Leverkusen',
 2685: 'Bologna',
 2686: 'Atalanta',
 2687: 'Juventus',
 2689: 'Lecce',
 2690: 'Parma',
 2692: 'AC Milan',
 2693: 'Fiorentina',
 2695: 'Udinese',
 2696: 'Torino',
 2697: 'Inter',
 2699: 'Lazio',
 2701: 'Hellas Verona',
 2702: 'AS Roma',
 2704: 'Como',
 2713: 'Genoa',
 2714: 'SSC Napoli',
 2719: 'Cagliari',
 2737: 'Pisa',
 2761: 'Cremonese',
 2793: 'Sassuolo',
 2814: 'Espanyol',
 2816: 'Real Betis',
 2817: 'FC Barcelona',
 2818: 'Rayo Vallecano',
 2819: 'Villarreal',
 2820: 'Osasuna',
 2821: 'Celta Vigo',
 2824: 'Real Sociedad',
 2825: 'Athletic Club',
 2826: 'Mallorca',
 2828: 'Valencia',
 2829: 'Real Madrid',
 2833: 'Sevilla',
 2836: 'Atlético Madrid',
 2846: 'Elche',
 2849: 'Levante UD',
 2851: 'Real Oviedo',
 2859: 'Getafe',
 2885: 'Deportivo Alavés',
 5885: '1. FC Heidenheim',
 6070: 'Paris FC',
 6925: 'Rodez AF',
 24264: 'Girona FC',
 36360: 'RB Leipzig'}

In [53]:
def apply_2026_overrides(row):
    p_id = row['player id']
    if p_id in player_team_ids:
        target_id = player_team_ids[p_id]
        row['team id'] = target_id
        row['team'] = team_id_to_name.get(target_id, row['team'])
    return row

df_26 = df_26.apply(apply_2026_overrides, axis=1)

In [54]:
df_26['rating_points'] = df_26['rating'] * df_26['appearances']
df_25['rating_points'] = df_25['rating'] * df_25['appearances']
df_24['rating_points'] = df_24['rating'] * df_24['appearances']

C:\Users\vibha\AppData\Local\Temp\ipykernel_23496\3941667240.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_26['rating_points'] = df_26['rating'] * df_26['appearances']
C:\Users\vibha\AppData\Local\Temp\ipykernel_23496\3941667240.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_25['rating_points'] = df_25['rating'] * df_25['appearances']
C:\Users\vibha\AppData\Local\Temp\ipykernel_23496\3941667240.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_24['rating_points'] = df_24['rating'] * df_24['appearances']

In [55]:
metadata_columns = ['player', 'team', 'player id', 'team id', 'league', 'season', 'position']

percentage_columns = [
    'accurateCrossesPercentage', 'accurateLongBallsPercentage', 'accuratePassesPercentage',
    'aerialDuelsWonPercentage', 'groundDuelsWonPercentage', 'goalConversionPercentage',
    'penaltyConversion', 'setPieceConversion', 'successfulDribblesPercentage',
    'tacklesWonPercentage', 'totalDuelsWonPercentage'
]

special_exclusions = [
    'rating', 'totalRating', 'countRating', 'scoringFrequency'
]

In [ ]:
percentage_formula_map = {
    'accurateCrossesPercentage': ('accurateCrosses', 'totalCross'),
    'accurateLongBallsPercentage': ('accurateLongBalls', 'totalLongBalls'),
    'accuratePassesPercentage': ('accuratePasses', 'totalPasses'),
    'successfulDribblesPercentage': ('successfulDribbles', 'totalContest'),
    'tacklesWonPercentage': ('tacklesWon', 'tackles'),
    'goalConversionPercentage': ('goals', 'totalShots'),
    
    'penaltyConversion': ('penaltyGoals', 'penaltiesTaken'),
    'setPieceConversion': ('freeKickGoal', 'shotFromSetPiece'),
    
    'aerialDuelsWonPercentage': ('aerialDuelsWon', 'aerialDuelsWon + aerialLost'),
    'groundDuelsWonPercentage': ('groundDuelsWon', 'groundDuelsWon + duelLost'),
    'totalDuelsWonPercentage': ('totalDuelsWon', 'totalDuelsWon + duelLost'),
    
    'scoringFrequency': ('minutesPlayed', 'goals')
}

In [57]:
agg_rules = {
    'player': 'last',
    'team': 'last',
    'team id': 'last',
    'league': 'last',
    'season': 'last',
    'position': 'last',
    'appearances': 'sum',
    'rating_points': 'sum' 
}

In [ ]:
sum_column=df_26.columns.to_list()
for item in special_exclusions + metadata_columns + percentage_columns:    
    sum_column.remove(item)

In [66]:
for col in sum_column:
    if col not in agg_rules:
        agg_rules[col] = 'sum'

In [67]:
df_26_flat = df_26.groupby('player id').agg(agg_rules).reset_index()
df_25_flat = df_25.groupby('player id').agg(agg_rules).reset_index()
df_24_flat = df_24.groupby('player id').agg(agg_rules).reset_index()

In [68]:
for df_flat in [df_26_flat, df_25_flat, df_24_flat]:
    df_flat['rating'] = np.where(
        df_flat['appearances'] > 0,
        df_flat['rating_points'] / df_flat['appearances'],
        0.0
    )

In [70]:
df_26_flat.shape

(2691, 104)

In [71]:
df_26.shape

(2773, 118)