In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [19]:
df=pd.read_csv('../../../data/raw/matches/training_matches_2025.csv')

In [20]:
df.head()

,match_id,date,competition_code,matchday,home_team,away_team,home_goals,away_goals,goal_difference,match_result,winner_team,loser_team
0,537785,2025-08-15T19:00:00Z,PL,1.0,Liverpool FC,AFC Bournemouth,4,2,2,HOME_WIN,Liverpool FC,AFC Bournemouth
1,537786,2025-08-16T11:30:00Z,PL,1.0,Aston Villa FC,Newcastle United FC,0,0,0,DRAW,NONE,NONE
2,537787,2025-08-16T14:00:00Z,PL,1.0,Brighton & Hove Albion FC,Fulham FC,1,1,0,DRAW,NONE,NONE
3,537789,2025-08-16T14:00:00Z,PL,1.0,Sunderland AFC,West Ham United FC,3,0,3,HOME_WIN,Sunderland AFC,West Ham United FC
4,537790,2025-08-16T14:00:00Z,PL,1.0,Tottenham Hotspur FC,Burnley FC,3,0,3,HOME_WIN,Tottenham Hotspur FC,Burnley FC

In [21]:
df.columns.to_list()

['match_id',
 'date',
 'competition_code',
 'matchday',
 'home_team',
 'away_team',
 'home_goals',
 'away_goals',
 'goal_difference',
 'match_result',
 'winner_team',
 'loser_team']

In [22]:
df=df.drop(columns=['loser_team','winner_team','matchday','match_result','home_goals','away_goals','match_id','date'])

In [23]:
df.shape

(2919, 4)

In [24]:
count=0
for idx in df.index:
    if count%2==0:
        home = df.at[idx, 'home_team']
        away = df.at[idx, 'away_team']
        
        df.at[idx, 'home_team'] = away
        df.at[idx, 'away_team'] = home
        
        df.at[idx, 'goal_difference'] = -df.at[idx, 'goal_difference']
        
    count+=1

In [25]:
df.head()

,competition_code,home_team,away_team,goal_difference
0,PL,AFC Bournemouth,Liverpool FC,-2
1,PL,Aston Villa FC,Newcastle United FC,0
2,PL,Fulham FC,Brighton & Hove Albion FC,0
3,PL,Sunderland AFC,West Ham United FC,3
4,PL,Burnley FC,Tottenham Hotspur FC,-3

In [39]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    temp_set=set(df['home_team'].drop_duplicates())
    temp_set.update(df['away_team'].drop_duplicates())
    display(temp_set)

{'1. FC Heidenheim 1846',
 '1. FC Köln',
 '1. FC Union Berlin',
 '1. FSV Mainz 05',
 'AC Milan',
 'AC Pisa 1909',
 'ACF Fiorentina',
 'AFC Ajax',
 'AFC Bournemouth',
 'AJ Auxerre',
 'AS Monaco FC',
 'AS Roma',
 'AVS',
 'AZ',
 'Angers SCO',
 'Arsenal FC',
 'Aston Villa FC',
 'Atalanta BC',
 'Athletic Club',
 'Bayer 04 Leverkusen',
 'Birmingham City FC',
 'Blackburn Rovers FC',
 'Bologna FC 1909',
 'Borussia Dortmund',
 'Borussia Mönchengladbach',
 'Brentford FC',
 'Brighton & Hove Albion FC',
 'Bristol City FC',
 'Burnley FC',
 'CA Osasuna',
 'CD Nacional',
 'CD Santa Clara',
 'CD Tondela',
 'CF Estrela da Amadora',
 'Cagliari Calcio',
 'Casa Pia AC',
 'Charlton Athletic FC',
 'Chelsea FC',
 'Club Atlético de Madrid',
 'Como 1907',
 'Coventry City FC',
 'Crystal Palace FC',
 'Deportivo Alavés',
 'Derby County FC',
 'Eintracht Frankfurt',
 'Elche CF',
 'Everton FC',
 'FC Alverca',
 'FC Arouca',
 'FC Augsburg',
 'FC Barcelona',
 'FC Bayern München',
 'FC Famalicão',
 'FC Groningen',
 'FC Internazionale Milano',
 'FC Lorient',
 'FC Metz',
 'FC Nantes',
 'FC Porto',
 'FC St. Pauli 1910',
 "FC Twente '65",
 'FC Utrecht',
 'FC Volendam',
 'Feyenoord Rotterdam',
 'Fortuna Sittard',
 'Fulham FC',
 'GD Estoril Praia',
 'Genoa CFC',
 'Getafe CF',
 'Gil Vicente FC',
 'Girona FC',
 'Go Ahead Eagles',
 'Hamburger SV',
 'Hellas Verona FC',
 'Heracles Almelo',
 'Hull City AFC',
 'Ipswich Town FC',
 'Juventus FC',
 'Le Havre AC',
 'Leeds United FC',
 'Leicester City FC',
 'Levante UD',
 'Lille OSC',
 'Liverpool FC',
 'Manchester City FC',
 'Manchester United FC',
 'Middlesbrough FC',
 'Millwall FC',
 'Moreirense FC',
 'NAC Breda',
 'NEC',
 'Newcastle United FC',
 'Norwich City FC',
 'Nottingham Forest FC',
 'OGC Nice',
 'Olympique Lyonnais',
 'Olympique de Marseille',
 'Oxford United FC',
 'PEC Zwolle',
 'PSV',
 'Paris FC',
 'Paris Saint-Germain FC',
 'Parma Calcio 1913',
 'Portsmouth FC',
 'Preston North End FC',
 'Queens Park Rangers FC',
 'RB Leipzig',
 'RC Celta de Vigo',
 'RC Strasbourg Alsace',
 'RCD Espanyol de Barcelona',
 'RCD Mallorca',
 'Racing Club de Lens',
 'Rayo Vallecano de Madrid',
 'Real Betis Balompié',
 'Real Madrid CF',
 'Real Oviedo',
 'Real Sociedad de Fútbol',
 'Rio Ave FC',
 'SBV Excelsior',
 'SC Freiburg',
 'SC Heerenveen',
 'SS Lazio',
 'SSC Napoli',
 'SV Werder Bremen',
 'Sevilla FC',
 'Sheffield United FC',
 'Sheffield Wednesday FC',
 'Southampton FC',
 'Sparta Rotterdam',
 'Sport Lisboa e Benfica',
 'Sporting Clube de Braga',
 'Sporting Clube de Portugal',
 'Stade Brestois 29',
 'Stade Rennais FC 1901',
 'Stoke City FC',
 'Sunderland AFC',
 'Swansea City AFC',
 'TSG 1899 Hoffenheim',
 'Telstar 1963',
 'Torino FC',
 'Tottenham Hotspur FC',
 'Toulouse FC',
 'US Cremonese',
 'US Lecce',
 'US Sassuolo Calcio',
 'Udinese Calcio',
 'Valencia CF',
 'VfB Stuttgart',
 'VfL Wolfsburg',
 'Villarreal CF',
 'Vitória SC',
 'Watford FC',
 'West Bromwich Albion FC',
 'West Ham United FC',
 'Wolverhampton Wanderers FC',
 'Wrexham AFC'}

In [29]:
df_sofa=pd.read_csv('../../../data/processed/major_leagues/Sofascore_player_data_2526.csv')

In [30]:
df_sofa.head()

,accuratechippedpasses,accuratecrosses,accuratecrossespercentage,accuratefinalthirdpasses,accuratelongballs,accuratelongballspercentage,accurateoppositionhalfpasses,accurateownhalfpasses,accuratepasses,accuratepassespercentage,...,inside_box_shot_pct_zscore,assist_conversion_zscore,xa_per_keypass_zscore,final_third_pass_pct_zscore,opp_half_pass_pct_zscore,dribbles_per_touch_zscore,dispossessed_per_touch_zscore,possession_lost_per_touch_zscore,defensive_actions_zscore,defensive_actions_per90_zscore
0,48.0,0.0,0.0,51.0,248.0,35.63,173.0,672.0,845.0,65.25,...,-0.204124,-0.380008,0.898225,-0.425200,-0.016119,2.797916,-0.204124,-0.121965,0.806981,-0.127004
1,70.0,0.0,0.0,50.0,197.0,34.99,103.0,1075.0,1178.0,76.05,...,-0.204124,-0.380008,1.377582,-0.916766,-1.375336,0.456518,-0.204124,-1.244945,1.206038,0.482156
2,31.0,0.0,0.0,52.0,168.0,32.81,120.0,372.0,492.0,58.16,...,-0.204124,-0.380008,-0.882246,0.819101,0.437759,1.199059,-0.204124,0.784275,-0.509906,1.002012
3,76.0,0.0,0.0,14.0,128.0,43.39,56.0,650.0,706.0,80.32,...,-0.204124,-0.380008,2.199338,-1.537456,-1.469385,2.671303,-0.204124,-1.987010,-0.070943,-1.421247
4,40.0,0.0,0.0,38.0,193.0,33.80,151.0,405.0,556.0,59.09,...,-0.204124,-0.380008,-0.882246,-0.205897,0.758513,-0.540049,-0.204124,0.793021,-0.203962,-1.292644

In [46]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(df_sofa[['team id','team']].drop_duplicates().style.hide())

In [56]:
team_id_to_name = {
    'Brentford FC': 50,
    'Brighton & Hove Albion FC': 30,
    'Leeds United FC': 34,
    'Manchester City FC': 17,
    'Manchester United FC': 35,
    'Everton FC': 48,
    'Burnley FC': 6,
    'Sunderland AFC': 41,
    'Aston Villa FC': 40,
    'Crystal Palace FC': 7,
    'Fulham FC': 43,
    'Chelsea FC': 38,
    'Arsenal FC': 42,
    'Newcastle United FC': 39,
    'Wolverhampton Wanderers FC': 3,
    'AFC Bournemouth': 60,
    'Tottenham Hotspur FC': 33,
    'Liverpool FC': 44,
    'West Ham United FC': 37,
    'Nottingham Forest FC': 14,
    'Elche CF': 2846,
    'FC Barcelona': 2817,
    'Levante UD': 2849,
    'Real Oviedo': 2851,
    'Getafe CF': 2859,
    'RCD Espanyol de Barcelona': 2814,
    'Club Atlético de Madrid': 2836,
    'Valencia CF': 2828,
    'Girona FC': 24264,
    'RCD Mallorca': 2826,
    'Villarreal CF': 2819,
    'CA Osasuna': 2820,
    'RC Celta de Vigo': 2821,
    'Rayo Vallecano de Madrid': 2818,
    'Real Betis Balompié': 2816,
    'Sevilla FC': 2833,
    'Real Madrid CF': 2829,
    'Deportivo Alavés': 2885,
    'Real Sociedad de Fútbol': 2824,
    'Athletic Club': 2825,
    '1. FSV Mainz 05': 2556,
    'Borussia Mönchengladbach': 2527,
    'Bayer 04 Leverkusen': 2681,
    'VfL Wolfsburg': 2524,
    'VfB Stuttgart': 2677,
    'FC Bayern München': 2672,
    'Hamburger SV': 2676,
    'Borussia Dortmund': 2673,
    '1. FC Köln': 2671,
    'SV Werder Bremen': 2534,
    'FC St. Pauli 1910': 2526,
    'SC Freiburg': 2538,
    'RB Leipzig': 36360,
    'FC Augsburg': 2600,
    'Eintracht Frankfurt': 2674,
    '1. FC Heidenheim 1846': 5885,
    'TSG 1899 Hoffenheim': 2569,
    '1. FC Union Berlin': 2547,
    'Atalanta BC': 2686,
    'AC Milan': 2692,
    'Como 1907': 2704,
    'SS Lazio': 2699,
    'Bologna FC 1909': 2685,
    'US Sassuolo Calcio': 2793,
    'AS Roma': 2702,
    'Torino FC': 2696,
    'US Cremonese': 2761,
    'Parma Calcio 1913': 2690,
    'Cagliari Calcio': 2719,
    'US Lecce': 2689,
    'Udinese Calcio': 2695,
    'ACF Fiorentina': 2693,
    'AC Pisa 1909': 2737,
    'Genoa CFC': 2713,
    'FC Internazionale Milano': 2697,
    'Juventus FC': 2687,
    'SSC Napoli': 2714,
    'Hellas Verona FC': 2701,
    'Angers SCO': 1684,
    'Lille OSC': 1643,
    'Paris Saint-Germain FC': 1644,
    'Stade Brestois 29': 1715,
    'FC Nantes': 1647,
    'Olympique de Marseille': 1641,
    'Racing Club de Lens': 1648,
    'OGC Nice': 1661,
    'AJ Auxerre': 1646,
    'Le Havre AC': 1662,
    'Olympique Lyonnais': 1649,
    'FC Lorient': 1656,
    'FC Metz': 1651,
    'Stade Rennais FC 1901': 1658,
    'Paris FC': 6070,
    'AS Monaco FC': 1653,
    'RC Strasbourg Alsace': 1659,
    'Toulouse FC': 1681,
    'Southampton FC': 45,
    'Stoke City FC': 29,
    'Swansea City AFC': 74,
    'Coventry City FC': 11,
    'Derby County FC': 27,
    'Sheffield Wednesday FC': 12,
    'Preston North End FC': 21,
    'Bristol City FC': 58,
    'Millwall FC': 25,
    'Charlton Athletic FC': 47,
    'Norwich City FC': 263,
    'Hull City AFC': 96,
    'Watford FC': 24,
    'Wrexham AFC': 64,
    'Ipswich Town FC': 32,
    'Oxford United FC': 95,
    'Portsmouth FC': 2,
    'Sheffield United FC': 15,
    'Leicester City FC': 31,
    'Blackburn Rovers FC': 46,
    'West Bromwich Albion FC': 8,
    'Middlesbrough FC': 36,
    'Queens Park Rangers FC': 1,
    'Birmingham City FC': 9,
    'Telstar 1963': 2972,
    'Sparta Rotterdam': 2960,
    'Go Ahead Eagles': 2979,
    'SBV Excelsior': 2967,
    'AFC Ajax': 2953,
    'NAC Breda': 2947,
    'FC Volendam': 2968,
    'FC Utrecht': 2948,
    'NEC': 2962,
    'PSV': 2952,
    'Heracles Almelo': 2977,
    'AZ': 2950,
    'Fortuna Sittard': 2957,
    'Feyenoord Rotterdam': 2959,
    "FC Twente '65": 2955,
    'FC Groningen': 2951,
    'SC Heerenveen': 2964,
    'PEC Zwolle': 2971,
    'AVS': 483088,
    'Moreirense FC': 3014,
    'FC Famalicão': 49531,
    'Gil Vicente FC': 3010,
    'Sporting Clube de Portugal': 3001,
    'FC Porto': 3002,
    'CD Tondela': 38396,
    'Rio Ave FC': 3036,
    'CD Nacional': 3013,
    'Vitória SC': 3009,
    'Sporting Clube de Braga': 2999,
    'Sport Lisboa e Benfica': 3006,
    'CD Santa Clara': 3011,
    'CF Estrela da Amadora': 3035,
    'FC Alverca': 190328,
    'FC Arouca': 25777,
    'Casa Pia AC': 36365,
    'GD Estoril Praia': 4500,
}

In [57]:
df['home_id']=df["home_team"].map(team_id_to_name)

In [58]:
df['away_id']=df["away_team"].map(team_id_to_name)

In [59]:
df.head()

,competition_code,home_team,away_team,goal_difference,home_id,away_id
0,PL,AFC Bournemouth,Liverpool FC,-2,60,44
1,PL,Aston Villa FC,Newcastle United FC,0,40,39
2,PL,Fulham FC,Brighton & Hove Albion FC,0,43,30
3,PL,Sunderland AFC,West Ham United FC,3,41,37
4,PL,Burnley FC,Tottenham Hotspur FC,-3,6,33

In [60]:
df.isnull().sum()

competition_code    0
home_team           0
away_team           0
goal_difference     0
home_id             0
away_id             0
dtype: int64

In [61]:
df.to_csv('../../../data/processed/Matches/Matches_cleaned_2526.csv',index=False)