In [29]:
import pandas as pd
import sys
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sys.path.append(r"D:/Football Project/src")

import feature_lists_3yr as fl

In [30]:
df=pd.read_csv("D:/Football Project/data/processed/3_year/EWMA_Top5_Leagues.csv")

In [31]:
df=df[df['position']=='Goalkeepers']

In [32]:
df.head()

,player id,player,team,team id,league,position,number_of_seasons,appearances,accuratechippedpasses,accuratecrosses,...,assist_conversion,xa_per_keypass,final_third_pass_pct,opp_half_pass_pct,dribbles_per_touch,dispossessed_per_touch,possession_lost_per_touch,defensive_actions,defensive_actions_per90,weak_foot_goals_pct
1,2899,Daniele Padelli,Udinese,2695,Italy Serie A,Goalkeepers,2,1.666667,0.666667,0.0,...,NaN,NaN,0.000000,0.051546,0.000000,0.000000,0.267045,13.000000,7.800000,NaN
4,8959,Manuel Neuer,FC Bayern München,2672,Germany Bundesliga,Goalkeepers,3,22.142857,60.857143,0.0,...,0.0,0.155,0.030907,0.093407,0.000466,0.000000,0.145497,172.428571,8.074179,NaN
7,15219,Lukáš Hrádecký,AS Monaco,1653,France Ligue 1,Goalkeepers,3,22.714286,43.571429,0.0,...,NaN,NaN,0.021955,0.116638,0.000000,0.000000,0.229590,166.857143,7.533324,NaN
9,16206,Yann Sommer,Inter,2697,Italy Serie A,Goalkeepers,3,33.142857,53.000000,0.0,...,NaN,NaN,0.014098,0.074206,0.000000,0.000000,0.134918,209.285714,6.325561,NaN
15,22209,Ørjan Nyland,Sevilla,2833,Spain La Liga,Goalkeepers,3,14.857143,18.714286,0.0,...,0.0,0.024,0.073505,0.203511,0.000000,0.001033,0.313791,106.714286,7.222819,NaN

In [33]:
creation_to_keep = ['accurateoppositionhalfpasses_per90', 'accuratelongballspercentage', 'accuratelongballs_per90', 'assists_per90', 'totalpasses_per90', 'passtoassist_per90', 'accuratepassespercentage']
possession_to_keep = ['touches_per90', 'possesionlost_per90', 'interceptions_per90', 'blockedshots_per90', 'errorleadtogoal_90', 'errorleadtoshot_per90', 'dribbledpad_per90']
duels_to_keep = ['aerialduelswonpercentage', 'aerialduelswon_per90']
discipline_to_keep = ['owngoals_per90']

columns_to_drop = (
    fl.attacking_features +
    [col for col in fl.creation_features if col not in creation_to_keep] +
    [col for col in fl.possession_features if col not in possession_to_keep] +
    [col for col in fl.duel_features if col not in duels_to_keep] +
    [col for col in fl.discipline_features if col not in discipline_to_keep]
)

df = df.drop(columns=columns_to_drop)

In [34]:
df = df[df["minutesplayed"]>270]

In [35]:
df.shape

(154, 69)

In [36]:
df.head()

,player id,player,team,team id,league,position,number_of_seasons,appearances,attemptpenaltymiss,attemptpenaltypost,...,possessionwonattthird_per90,clearances_per90,blockedshots_per90,dribbledpast_per90,errorleadtoshot_per90,errorleadtogoal_per90,aerialduelswon_per90,owngoals_per90,defensive_actions,defensive_actions_per90
4,8959,Manuel Neuer,FC Bayern München,2672,Germany Bundesliga,Goalkeepers,3,22.142857,0.0,0.0,...,0.0,0.662257,0.0,0.000000,0.100342,0.120410,0.140479,0.0,172.428571,8.074179
7,15219,Lukáš Hrádecký,AS Monaco,1653,France Ligue 1,Goalkeepers,3,22.714286,0.0,0.0,...,0.0,0.657876,0.0,0.019349,0.019349,0.045148,0.219292,0.0,166.857143,7.533324
9,16206,Yann Sommer,Inter,2697,Italy Serie A,Goalkeepers,3,33.142857,0.0,0.0,...,0.0,0.466321,0.0,0.017271,0.025907,0.021589,0.064767,0.0,209.285714,6.325561
15,22209,Ørjan Nyland,Sevilla,2833,Spain La Liga,Goalkeepers,3,14.857143,0.0,0.0,...,0.0,0.850881,0.0,0.048346,0.048346,0.077353,0.319080,0.0,106.714286,7.222819
24,37096,Péter Gulácsi,RB Leipzig,36360,Germany Bundesliga,Goalkeepers,3,23.571429,0.0,0.0,...,0.0,1.131997,0.0,0.037319,0.024879,0.031099,0.223912,0.0,177.285714,7.718728

In [37]:
df_desc=df.drop(columns=fl.metadata_features).describe().transpose()

In [39]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(df_desc)

,count,mean,std,min,25%,50%,75%,max
number_of_seasons,154.0,2.441558,0.766854,1.000000,2.000000,3.000000,3.000000,3.000000
appearances,154.0,22.476314,10.502908,4.000000,12.107143,24.928571,31.928571,38.000000
attemptpenaltymiss,154.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
attemptpenaltypost,154.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
attemptpenaltytarget,154.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ballrecovery,154.0,181.361843,90.811170,26.000000,98.916667,199.714286,258.321429,334.000000
blockedshots,154.0,0.012678,0.079653,0.000000,0.000000,0.000000,0.000000,0.666667
cleansheet,154.0,5.871243,3.674144,0.000000,3.000000,5.761905,8.107143,16.857143
clearances,154.0,22.697774,12.352696,1.000000,12.607143,22.619048,32.392857,51.428571
crossesnotclaimed,154.0,0.340383,0.529785,0.000000,0.000000,0.142857,0.571429,3.000000
dribbledpast,154.0,0.805009,0.837209,0.000000,0.142857,0.666667,1.000000,5.000000
errorleadtogoal,154.0,1.080891,1.003113,0.000000,0.285714,1.000000,1.571429,6.000000
errorleadtoshot,154.0,1.070192,1.061801,0.000000,0.285714,0.785714,1.600000,4.571429
goalkicks,154.0,122.072665,65.465912,15.000000,68.571429,119.142857,174.607143,295.428571
goalsconceded,154.0,30.555411,15.154778,2.000000,19.607143,30.571429,42.928571,67.000000
goalsconcededinsidethebox,154.0,26.608411,13.412644,2.000000,16.035714,26.214286,37.321429,58.000000
goalsconcededoutsidethebox,154.0,3.947001,2.334224,0.000000,2.000000,3.714286,5.678571,10.000000
goalsprevented,154.0,0.271727,2.986886,-10.704286,-1.440714,-0.062571,1.597143,9.363333
highclaims,154.0,16.985652,10.906429,0.000000,8.297619,15.428571,23.535714,51.857143
interceptions,154.0,0.243166,0.376284,0.000000,0.000000,0.000000,0.535714,1.800000
matchesstarted,154.0,22.325727,10.628419,3.000000,12.050000,24.928571,31.928571,38.000000
minutesplayed,154.0,2006.360606,947.450595,315.000000,1089.607143,2243.571429,2844.214286,3420.000000
penaltyconceded,154.0,0.278850,0.385985,0.000000,0.000000,0.000000,0.571429,1.714286
penaltyfaced,154.0,3.428757,2.235011,0.000000,1.464286,3.428571,5.000000,10.333333
penaltysave,154.0,0.569635,0.649932,0.000000,0.000000,0.285714,1.000000,2.857143
penaltywon,154.0,0.000928,0.011512,0.000000,0.000000,0.000000,0.000000,0.142857
possessionwonattthird,154.0,0.006494,0.080582,0.000000,0.000000,0.000000,0.000000,1.000000
punches,154.0,9.899691,6.382346,0.000000,4.814286,8.690476,14.214286,28.000000
runsout,154.0,12.757885,8.868870,1.000000,6.000000,11.142857,17.571429,49.000000
savedshotsfrominsidethebox,154.0,43.187755,22.188361,5.000000,23.257143,47.428571,62.107143,84.714286
savedshotsfromoutsidethebox,154.0,20.848609,10.910508,0.000000,10.785714,22.214286,29.857143,46.571429
saves,154.0,65.128819,32.930561,6.000000,34.071429,72.142857,94.642857,118.600000
savescaught,154.0,0.558751,0.639804,0.000000,0.000000,0.428571,0.857143,4.000000
savesparried,154.0,14.135745,7.491095,1.000000,7.000000,14.285714,19.964286,31.666667
successfulrunsout,154.0,12.165925,8.618003,0.000000,5.857143,10.500000,16.714286,47.333333
tackles,154.0,0.615152,0.703551,0.000000,0.000000,0.500000,0.964286,4.000000
tackleswon,154.0,0.361905,0.472555,0.000000,0.000000,0.142857,0.571429,2.666667
totwappearances,154.0,1.189734,1.023106,0.000000,0.407143,1.000000,2.000000,4.857143
rating,154.0,7.007287,0.182461,6.280000,6.935845,7.015344,7.084978,7.830000
accuratelongballspercentage,154.0,38.756288,5.686768,25.804196,34.762142,38.676138,42.161627,62.182741
accuratepassespercentage,154.0,69.411772,8.692849,45.915940,63.826707,69.858282,75.371385,89.823278
tackleswonpercentage,154.0,39.547590,42.134064,0.000000,0.000000,33.333333,88.750000,100.000000
aerialduelswonpercentage,154.0,90.110597,15.125914,0.000000,85.824176,93.820797,100.000000,100.000000
assists_per90,154.0,0.003747,0.009685,0.000000,0.000000,0.000000,0.000000,0.062674
totalpasses_per90,154.0,32.133238,5.194376,21.612903,28.858151,30.996676,34.782425,53.636364
accurateoppositionhalfpasses_per90,154.0,3.710533,1.589892,1.106764,2.479576,3.456011,4.674120,8.454545
passtoassist_per90,154.0,0.000794,0.005494,0.000000,0.000000,0.000000,0.000000,0.045455
accuratelongballs_per90,154.0,5.916820,1.651945,3.000000,4.741987,5.706525,6.796247,12.454545
touches_per90,154.0,41.720461,5.527939,28.989247,38.217639,40.797514,44.945457,63.636364
tackles_per90,154.0,0.028746,0.036627,0.000000,0.000000,0.019935,0.041015,0.227273
tackleswon_per90,154.0,0.016320,0.023901,0.000000,0.000000,0.006723,0.023635,0.137931
interceptions_per90,154.0,0.009765,0.015569,0.000000,0.000000,0.000000,0.016246,0.092593
ballrecovery_per90,154.0,8.037730,1.125466,5.340153,7.236316,8.011495,8.776144,10.774194
possessionwonattthird_per90,154.0,0.000197,0.002442,0.000000,0.000000,0.000000,0.000000,0.030303
clearances_per90,154.0,1.039533,0.376666,0.200000,0.823163,1.000000,1.212435,3.200000
blockedshots_per90,154.0,0.000496,0.003133,0.000000,0.000000,0.000000,0.000000,0.023256
dribbledpast_per90,154.0,0.041733,0.051526,0.000000,0.007137,0.029828,0.056483,0.333333
errorleadtoshot_per90,154.0,0.046611,0.045151,0.000000,0.009073,0.036335,0.075784,0.255682
errorleadtogoal_per90,154.0,0.051092,0.050266,0.000000,0.013611,0.042286,0.066842,0.254597
aerialduelswon_per90,154.0,0.298591,0.152021,0.000000,0.196403,0.282222,0.384882,1.000000
owngoals_per90,154.0,0.003156,0.013179,0.000000,0.000000,0.000000,0.000000,0.142857
defensive_actions,154.0,182.220161,91.229051,26.000000,99.083333,200.642857,259.607143,335.000000
defensive_actions_per90,154.0,8.076241,1.132651,5.340153,7.244360,8.046764,8.869490,10.806452